# 用于推理的配置文件
tile_size: 512
pad_size: 32 #做expansion padding的时候的pad_siz

#推理相关

ratio: 0.6
device: 'cuda:0'
val_batch_size: 16
backbone: 'resnet50'
pretrained: True
pretrained_path: 'model_seed2022_fold0_epoch45_val0.3655_f1_score_0.8274.pth'

draw: False