# 用于推理的配置文件
tile_size: 512
pad_size: 32 #做expansion padding的时候的pad_siz

#推理相关

ratio: 0.5
device: 'cuda:0'
val_batch_size: 16
backbone: 'resnet18'
pretrained: True
pretrained_path: 'model_seed2022_fold0_epoch23_val0.4433_f1_score_0.7071.pth'

draw: False