# 用于推理的配置文件
tile_size: 512
pad_size: 64 #做expansion padding的时候的pad_siz

#推理相关

ratio: 0.7
device: 'cuda:2'
val_batch_size: 16
backbone: 'resnext50_32x4d'
pretrained: True
pretrained_path: 'model_seed2022_fold0_epoch50_val0.3795_f1_score_0.8571.pth'

draw: False