# baseline的配置文件
raw_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_image'
raw_train_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_train'
raw_val_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_val'
train_dir: '/data/cx/datasets/fujian_gis_data/train'
val_dir: '/data/cx/datasets/fujian_gis_data/val'
split_ratio: 0.8  #train val split ratio

#overlap tile params
shift_h: 0
shift_w: 0
tile_size: 512

#数据增强parmas
transform: True #是否使用数据增强
train_width: 512 #训练宽度尺寸 训练预处理会被resize到这一宽度
train_height: 512 #训练高度尺寸 训练预处理的时候会被resize到这一高度
val_width: 512 # 预测宽度尺寸 预测预处理的时候会被resize到这一宽度
val_height: 512 #预测高度尺寸 预测预处理的的时候会被resize到这一高度

#训练相关
device: 'cuda:0'
batch_size: 16
val_batch_size: 1
num_epochs: 20