# 用于推理的配置文件
tile_size: 512
pad_size: 64 #做expansion padding的时候的pad_siz

#推理相关

ratio: 0.45
device: 'cuda:2'
val_batch_size: 16
backbone: 'resnext50_32x4d'
pretrained: True
pretrained_path: 'model_seed2022_fold0_epoch41_val0.3924_f1_score_0.8459.pth'

draw: False