# baseline的配置文件
raw_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_image'
raw_train_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_train'
raw_val_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_val'
train_dir: '/data/cx/datasets/fujian_gis_data/train'
val_dir: '/data/cx/datasets/fujian_gis_data/val'
split_ratio: 0.8  #train val split ratio

#overlap tile params
shift_h: 0
shift_w: 0
tile_size: 512

#数据增强parmas
transform: True #是否使用数据增强
train_width: 512 #训练宽度尺寸 训练预处理会被resize到这一宽度
train_height: 512 #训练高度尺寸 训练预处理的时候会被resize到这一高度
val_width: 512 # 预测宽度尺寸 预测预处理的时候会被resize到这一宽度
val_height: 512 #预测高度尺寸 预测预处理的的时候会被resize到这一高度

#训练相关
device: 'cuda:6'
train_batch_size: 4
val_batch_size: 1
num_epochs: 20
backbone_name: 'seresnext101'
pretrained: False
pretrained_path: None
model_params:
  deep_supervision: False
  clf_head: True
  clf_threshold: None
  load_backbone_weights: True
optim_params:
  lr: 0.0001
  betas:  (0.9, 0.999)
  weight_decay: 0.00001
lr_scheduler_name: 'ReduceLROnPlateau'
sched_params:
  'factor': 0.8
  'patience': 5
  'min_lr': 1e-5
  'verbose': True
