
#数据增强parmas
train_width: 512 #训练宽度尺寸 训练预处理会被resize到这一宽度
train_height: 512 #训练高度尺寸 训练预处理的时候会被resize到这一高度
val_width: 512 # 预测宽度尺寸 预测预处理的时候会被resize到这一宽度
val_height: 512 #预测高度尺寸 预测预处理的的时候会被resize到这一高度

#训练相关
device: 'cuda:2'
val_batch_size: 16
pretrained: True
pretrained_path: '/data/cx/competition/fujian_bigdata_GIS_competition/raft_baseline/weights/model_seed2022_fold0_epoch24_val0.2275_f1_score_0.9039.pth'
dice_threshold: 0.5
model_params:
  deep_supervision: False
  clf_head: False
  clf_threshold: None
  load_backbone_weights: False
result_csv_path: '/data/cx/datasets/fujian_gis_data/'
weight_save_path: '/data/cx/competition/fujian_bigdata_GIS_competition/raft_baseline/weights'
