# baseline的配置文件
raw_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_image'
raw_train_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_train'
raw_val_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_val'
train_dir: '/data/cx/datasets/fujian_gis_data/train'
val_dir: '/data/cx/datasets/fujian_gis_data/val'
split_ratio: 0.8  #train val split ratio
#overlap tile params
shift_h: 0
shift_w: 0
tile_size: 512
