# baseline的配置文件
raw_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_image'
raw_train_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_train'
raw_val_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_val'
train_dir: '/data/cx/datasets/fujian_gis_data/train'
val_dir: '/data/cx/datasets/fujian_gis_data/val'
split_ratio: 0.8  #train val split ratio

#overlap tile params
shift_h: 64
shift_w: 64
tile_size: 256

#数据增强parmas
transform: True #是否使用数据增强
train_width: 256 #训练宽度尺寸 训练预处理会被resize到这一宽度
train_height: 256 #训练高度尺寸 训练预处理的时候会被resize到这一高度
val_width: 256 # 预测宽度尺寸 预测预处理的时候会被resize到这一宽度
val_height: 256 #预测高度尺寸 预测预处理的的时候会被resize到这一高度

#训练相关
device: 'cuda:6'
train_batch_size: 16
val_batch_size: 16
num_epochs: 20
backbone_name: 'seresnext101'
pretrained: False
pretrained_path: None
dice_threshold: 0.5
model_params:
  deep_supervision: False
  clf_head: False
  clf_threshold: None
  load_backbone_weights: True
optim_params:
  lr: 0.00001
  betas:  (0.9, 0.999)
  weight_decay: 0.0005
lr_scheduler_name: 'ReduceLROnPlateau'
sched_params:
  'factor': 0.5
  'patience': 2
  'min_lr': 1e-6
  'verbose': True
result_csv_path: '/data/cx/datasets/fujian_gis_data/'
weight_save_path: '/data/cx/competition/fujian_bigdata_GIS_competition/raft_baseline/weights'
save_best_num: 3 #保留val-loss最低的k个模型
