# baseline的配置文件
raw_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_image'
raw_train_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_train'
raw_val_dir: '/data/cx/datasets/fujian_gis_data/raw/raw_val'
train_dir: '/data/cx/datasets/fujian_gis_data/train'
val_dir: '/data/cx/datasets/fujian_gis_data/val'
split_ratio: 0.8  #train val split ratio

#overlap tile params
train_overlap_size: 256
val_overlap_size: 0
tile_size: 512

#数据增强parmas
transform: True #是否使用数据增强
train_width: 512 #训练宽度尺寸 训练预处理会被resize到这一宽度
train_height: 512 #训练高度尺寸 训练预处理的时候会被resize到这一高度
val_width: 512 # 预测宽度尺寸 预测预处理的时候会被resize到这一宽度
val_height: 512 #预测高度尺寸 预测预处理的的时候会被resize到这一高度

#训练相关
device: 'cuda:7'
train_batch_size: 16
val_batch_size: 16
num_epochs: 70
backbone: 'resnext50_32x4d'
pretrained: False
pretrained_path: None
dice_threshold: 0.5
model_params:
  deep_supervision: False
  clf_head: False
  clf_threshold: None
  load_backbone_weights: True
optim_params:
  lr: 0.000005
  betas:  (0.9, 0.999)
  weight_decay: 0.0005
lr_scheduler_name: 'ReduceLROnPlateau'
sched_params:
  'factor': 0.5
  'patience': 5
  'min_lr': 5e-7
  'verbose': True
result_csv_path: '/data/cx/datasets/fujian_gis_data/'
weight_save_path: '/data/cx/competition/fujian_bigdata_GIS_competition/raft_baseline/unet_weights'
save_best_num: 10 #保留val-loss最低的k个模型

#随机平衡采样配置
bucket_dir: './buckets'
sample_dir: './samples'
bucket_multiplier: 20
bucket_num_max: 4
min_bucket_size: 10
reset_bucket: True
